import os
import time


def sleep_clear(num):
  time.sleep(num)
  os.system("clear")


def print_dealing():
  print("\nDealing...\n🂡")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing... ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...  ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing... ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...  ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing... ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...  ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing... ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...  ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...   ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...    ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...     ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...      ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...       ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...        ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...         ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...          ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...           ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...            ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...             ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...              ♠️ ♥️ ♣️ ")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...               ♠️ ♥️ ♣️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...                ♠️ ♥️ ")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...                 ♠️ ♥️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...                  ♠️ ")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...                   ♠️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...                    ")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...                   ♠️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...                  ♠️ ")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...                 ♠️ ♥️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...                ♠️ ♥️ ")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...               ♠️ ♥️ ♣️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...              ♠️ ♥️ ♣️ ")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...             ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...            ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...           ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...          ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...         ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...        ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...       ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...      ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...     ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...    ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...   ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...  ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing... ♠️ ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...  ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing... ♥️ ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...  ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing... ♣️ ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing...  ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing... ♦️")
  sleep_clear(0.05)
  print("\n♠️ ♥️  LET'S PLAY BLACKJACK! ♣️ ♦️ \nDealing... ")
  sleep_clear(0.05)
